### ISSUE TITLE
tetris-hard-drop-patcher: include patch in .IPS format

### ISSUE THREAD

**Issue by LunarLambda** [stevebob/mos6502#1]
sha1 of used rom: a99f922e9da20b2a27e4398348505d2e9d15271b

Created using [Flips](https://github.com/Alcaro/Flips)

(zipped because of github's file limitations) [patch.zip](https://github.com/stevebob/mos6502/files/6177720/patch.zip)

**Comment by gridbugs** [comment]
Thanks. I've added the patch to the repo and added a link to the tetris-hard-drop-patcher readme.
